{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: ConfigMap*/}}
{{/*metadata:*/}}
{{/*  name: homebridge-settings*/}}
{{/*  namespace: {{ $.Release.Namespace }}*/}}
{{/*  labels:*/}}
{{/*    app: homebridge*/}}
{{/*data:*/}}
{{/*  settings.js: |*/}}
{{/*    {{- $.Values.homebridgeSettings | nindent 4 }}*/}}
