# Homebridge container configuration
image:
  repository: homebridge/homebridge
  tag: latest
  pullPolicy: Always

# Timezone configuration
timezone: "America/Chicago"

## Enable Avahi (mDNS) support
#enableAvahi: 0

# Resource requests and limits
resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 1500m

# Service configuration
nodePort:
  enabled: true

configFiles:
  config.json: |
    {
    }
  knx_config.json: |
    {
    }